api_platform:
  mapping:
    paths: [ '%kernel.project_dir%/src/Entity' ]
  patch_formats:
    json: [ 'application/merge-patch+json' ]
#    formats:
#      jsonld: [ 'application/ld+json' ]
#      json: [ 'application/json' ]
#      html: [ 'text/html' ]
#      yaml: [ 'application/x-yaml' ]
#      xml: [ 'application/xml', 'text/xml' ]
#      csv: [ 'text/csv' ]
  swagger:
    versions: [ 3 ]
